bug:
  comment: |
    Thanks for pointing out this bug! 
    We'll take a look and see what's going on.
    If you can, please give us a step-by-step on how it happens and any other info that could help.
