name: Build

on:
  push:
    branches: [ "main", "development", "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Build the library
      run: npm run build
