name: Build and Lint

on:
  push:
    branches-ignore:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: User Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4

        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # need to build before lint check because packages is using interlinked workspace dependencies
      - name: Build the packages
        id: build
        if: ${{ success() && !failure() }}
        run: pnpm build

      - name: Lint
        id: lint
        run: pnpm run lint

      - name: Linter Failed
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          script: |
            const { data: pullRequestData } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    commit_sha: context.payload.after
                })

              if(pullRequestData[0]){
                 await github.rest.issues.createComment({
                      issue_number: pullRequestData[0].number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: `### 🚨  Linter failed`
                  })
              } else {
                  throw new Error('Pull request data not found')
              }
