name: 'PR labeler'
on:
  pull_request_target:
jobs:
  pr-labeler:
    name: PR labeler
    runs-on: ubuntu-latest
    steps:
      - name: label-pr
        id: label-pr
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true