name: Build

on:
  release:

jobs:
  npm-publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: User Node.js LTS
        uses: actions/setup-node@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        id: lint
        run: pnpm run lint

      - name: Linter Failed
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          script: |
            const { pullRequestData: data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    commit_sha: context.payload.after
                })

              if(pullRequestData[0]){
                 await github.rest.issues.createComment({
                      issue_number: pullRequestData[0].number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: `### 🚨  Linter failed`
                  })
              } else {
                  throw new Error('Pull request data not found')
              }

      - name: Linter Failure Alert
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Linter failed while releasing new version of wapi.js. Check [HERE](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          SLACK_TITLE: "🚨🚨🚨 [WAPIJS.CO] MASTER BRANCH RELEASE FAILED 🚨🚨🚨"
          SLACK_USERNAME: sarthakjdev
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Build the packages
        if: ${{ success() && !failure()}}
        run: pnpm build

      - name: Build Failure Alert
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Build failed while releasing new version of wapi.js. Check [HERE](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          SLACK_TITLE: "🚨🚨🚨 [WAPIJS.CO] MASTER BRANCH BUILD FAILED 🚨🚨🚨"
          SLACK_USERNAME: sarthakjdev
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


      - name: publish-packages
        lint: publish
        env: 
           token: ${{ secrets.NPM_PUBLISH_TOKEN }}
        
