name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: write # because we want our workflow to update the package json of the packages with the latest version number

jobs:
  release:
    environment: Production
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: pnpm i --prod --frozen-lockfile --ignore-scripts

      - name: Build the packages
        run: pnpm build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npx semantic-release
