name: Publish Release
on:
  release:
    types: [released]
jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: pnpm i --prod --frozen-lockfile --ignore-scripts

      - name: Build dependencies
        run: pnpm run build

      - name: Extract package and semver from tag
        id: extract-tag
        uses: ./format-tag
        with:
          tag: ${{ github.ref_name }}

      - name: Publish package
        run: |
          pnpm --filter=${{ steps.extract-tag.outputs.subpackage == 'true' && '@wapijs/' || '' }}${{ steps.extract-tag.outputs.package }} publish --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
